### ISSUE TITLE
Ability to specify order of segments and prompt on one line

### ISSUE THREAD

**Issue by saxbophone** [puntonim/promptastic#23]
Hi, awesome project! I just couldn't get Powerline's git plugin configured on my Ubuntu box and this works a charm!
- One thing I think would be really useful is the ability to configure the order in which the prompt segments are displayed (maybe have config dictionary become an `OrderedDict`?).
- Also, I would really like to be able to type my commands on the same line as the prompt, i.e. not have the rest of the term window taken up by an empty blank line as does currently happen on my setup.

**My Setup:**

![promptastic](https://cloud.githubusercontent.com/assets/8693463/11258531/ca7a30a0-8e51-11e5-85b0-cac0eb94330d.png)

**Aim :smile::**

![zsh-git](http://devsnaps.herokuapp.com/images/zsh.jpg)

Let me know your thoughts, I might be able to hack on this project a bit :wink: :hammer:

**Comment by saxbophone** [comment]
Okay so after forking and hacking around on this project a bit I ended up with the prompt style I wanted which looks like this:

![screenshot from 2015-11-21 15-03-15](https://cloud.githubusercontent.com/assets/8693463/11319037/2af8310a-9061-11e5-92fe-2decda826d44.png)

You can see the diff from my fork and personal branch vs the main repo at master here: https://github.com/nimiq/promptastic/compare/master...saxbophone:personal-modifications?expand=1

Going forward, I wonder if it would be worth adding to this project the ability to customise the appearance of the prompt without having to hack around with the Python functions and classes in the codebase, but rather from just editing the config file? If you think this would be a worthwhile feature then I'd be happy to spend some time working on this feature myself.

**Comment by nimiq** [comment]
Hey Joshua, I like your suggestions and your work!
Honestly I intentionally split the prompt into 2 lines, cause I like the cursor the be always in the same position, so my eyes always know where to find it quickly.
But any extra feature/configuration that you want to add and that doesn't break the current features is more than welcome, so feel free to open pull requests!

Good luck and thank you for your contribution!
Paolo
